[build]
builder = "dockerfile"
dockerfilePath = "apps/server/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"

[environments]
  [environments.production]
  numReplicas = 1
  port = 3000
  
  [environments.development]
  numReplicas = 1
  port = 3000
